---
- name: first playbook
  hosts: all
  become: yes
  tasks:
    - name: install httpd software
      yum:
        name: httpd
        state: latest
    - name: start web server
      service:
        name: httpd

        state: started gmae
        fde6e2c41685d7c2200fc036c268b6051999a93c
        ashish: ranjan ranjan
